// ---------------------------------------------------------------------------
// Enums (DATA-MODEL §3 — 22 enums)
// ---------------------------------------------------------------------------

export type UserRole = 'admin' | 'collaborator'
export type ProfileStatus = 'active' | 'inactive' | 'pending'
export type JobTitle = 'sdr' | 'closer' | 'social_seller' | 'supervisor' | 'manager'
export type MetricType =
  | 'sale'
  | 'meeting_scheduled'
  | 'meeting_held'
  | 'call'
  | 'crm_update'
  | 'lead_recovery'
  | 'upsell'
  | 'amount_step'
  | 'weekly_goal'
  | 'monthly_goal'
  | 'activity'
  | 'custom'
export type RuleTriggerKind = 'manual' | 'auto_amount_step' | 'auto_goal'
export type EntrySource =
  'rule' | 'manual' | 'system' | 'mission' | 'challenge' | 'wheel' | 'reward' | 'achievement'
export type MissionKind = 'daily' | 'weekly' | 'special' | 'lightning'
export type MissionTargetKind = 'count' | 'amount'
export type MissionAudience = 'all' | 'selected'
export type ChallengeKind = 'duel' | 'team'
export type ChallengeMetric = 'meetings_held' | 'sales_count' | 'revenue' | 'points' | 'activities'
export type ChallengeStatus = 'draft' | 'active' | 'finished' | 'cancelled'
export type WheelKind = 'classic' | 'premium'
export type PrizeKind =
  'points' | 'coins' | 'cash' | 'voucher' | 'extra_spin' | 'multiplier' | 'mystery' | 'custom'
export type QueueStatus = 'waiting' | 'active' | 'done' | 'removed'
export type QueueSource = 'manual' | 'earned'
export type SpinStatus = 'pending' | 'approved' | 'rejected'
export type RedemptionSource = 'store' | 'wheel'
export type RedemptionStatus = 'requested' | 'approved' | 'delivered' | 'cancelled'
export type AchievementCriteria =
  | 'first_sale'
  | 'streak_days'
  | 'sales_total'
  | 'monthly_goal'
  | 'rank_first'
  | 'points_total'
  | 'missions_completed'
export type AchievementScope = 'lifetime' | 'season'
export type FeedKind =
  | 'sale'
  | 'achievement'
  | 'wheel_prize'
  | 'level_up'
  | 'mission_completed'
  | 'challenge_finished'
  | 'season_closed'
export type NotificationKind =
  | 'ranking'
  | 'mission'
  | 'reward'
  | 'wheel'
  | 'challenge'
  | 'achievement'
  | 'level'
  | 'event'
  | 'season'
  | 'system'
export type AuditAction = 'insert' | 'update' | 'delete' | 'rpc'
