import type { VProfileStats } from '@/lib/database.types'

/** Linha de `v_profile_stats` para testes — nome genérico, zero em tudo (banco recém-instalado). Nunca dados fictícios. */
export function makeProfileStats(over: Partial<VProfileStats> = {}): VProfileStats {
  return {
    profile_id: '00000000-0000-4000-8000-000000000001',
    season_id: 's1',
    full_name: 'Usuário de Teste',
    avatar_path: null,
    color: 'var(--avatar-fallback)',
    job_title: 'closer',
    team: null,
    role: 'admin',
    status: 'active',
    email: 'teste@exemplo.com',
    phone: null,
    season_name: 'Setembro',
    season_starts_at: '2026-09-01T03:00:00Z',
    season_ends_at: '2026-10-01T03:00:00Z',
    season_is_active: true,
    points: 0,
    points_earned: 0,
    sales_amount: 0,
    sales_count: 0,
    meetings_scheduled: 0,
    meetings_held: 0,
    calls: 0,
    crm_updates: 0,
    lead_recoveries: 0,
    upsells: 0,
    activities_count: 0,
    missions_completed: 0,
    conversion_pct: null,
    attendance_pct: null,
    goal_amount: 0,
    goal_pct: null,
    goal_missing_amount: 0,
    projected_goal_date: null,
    xp_per_level: 400,
    level: 1,
    xp_in_level: 0,
    xp_to_next: 400,
    coins_balance: 0,
    coins_earned_lifetime: 0,
    coins_spent_lifetime: 0,
    streak_days: 0,
    best_streak_days: 0,
    sales_amount_lifetime: 0,
    sales_count_lifetime: 0,
    rank: null,
    gap_to_above: null,
    is_tied_with_above: false,
    has_points: false,
    achievements_unlocked: 0,
    achievements_total: 6,
    pending_earned_spins: 0,
    last_entry_at: null,
    ...over,
  }
}
