import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { BookOpen, CheckCircle2, CircleDollarSign, Dices, Pencil, Plus, Save, ShieldCheck, Swords, Trash2, Trophy, X, Zap } from "lucide-react";
import "./admin-config-center.css";

type Rule={id:string;name:string;points:number;active:boolean};
type Challenge={id:string;name:string;description:string;type:"Duelo"|"Coletivo";metric:string;target:string;reward:string;period:string;participants:string;active:boolean};
type WheelConfig={classic:string[];premium:string[]};
type AdminCustomPage="wheel"|"guide"|null;
const RULES_KEY="orbion-point-rules-v2";
const CHALLENGES_KEY="orbion-challenges-v2";
export const WHEEL_KEY="orbion-wheel-prizes-v2";
const defaultRules:Rule[]=[
{id:"scheduled",name:"Reunião agendada",points:10,active:true},{id:"held",name:"Reunião realizada",points:20,active:true},{id:"sale",name:"Venda realizada",points:100,active:true},{id:"10k",name:"R$ 10.000 vendidos",points:150,active:true},{id:"weekly",name:"Meta semanal",points:200,active:true},{id:"monthly",name:"Meta mensal",points:500,active:true},{id:"crm",name:"CRM atualizado",points:10,active:true},{id:"recovery",name:"Recuperação de lead",points:30,active:true},{id:"upsell",name:"Upsell",points:80,active:true}
];
const defaultChallenges:Challenge[]=[
{id:"duel",name:"Duelo de reuniões",description:"Quem realizar mais reuniões até sexta-feira.",type:"Duelo",metric:"Reuniões",target:"Maior número",reward:"+300 pontos",period:"Até sexta-feira",participants:"Marcelo x Lucas",active:true},
{id:"team",name:"Desafio do time",description:"Bater a meta coletiva de vendas da semana.",type:"Coletivo",metric:"Faturamento",target:"R$ 50.000",reward:"Roleta Premium para todos",period:"Semana atual",participants:"Todo o time",active:true}
];
export const defaultWheel:WheelConfig={classic:["R$ 10 PIX","100 pontos","R$ 20 PIX","Giro extra","R$ 30 iFood","200 pontos"],premium:["R$ 50 PIX","500 pontos","R$ 100 PIX","Giro extra","R$ 50 iFood","1.000 pontos","2x pontos","Mystery Box"]};
function read<T>(key:string,fallback:T):T{try{const value=localStorage.getItem(key);return value?JSON.parse(value) as T:fallback}catch{return fallback}}
function save<T>(key:string,value:T){localStorage.setItem(key,JSON.stringify(value))}
export function AdminConfigCenter(){
 const [customPage,setCustomPage]=useState<AdminCustomPage>(null);const [host,setHost]=useState<HTMLElement|null>(null);const [section,setSection]=useState<"points"|"challenges"|null>(null);const [rules,setRules]=useState<Rule[]>(()=>read(RULES_KEY,defaultRules));const [challenges,setChallenges]=useState<Challenge[]>(()=>read(CHALLENGES_KEY,defaultChallenges));const [wheel,setWheel]=useState<WheelConfig>(()=>read(WHEEL_KEY,defaultWheel));const [ruleEdit,setRuleEdit]=useState<Rule|null>(null);const [challengeEdit,setChallengeEdit]=useState<Challenge|null>(null);const [toast,setToast]=useState<string|null>(null);
 const flash=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(null),2400)};
 useEffect(()=>{
  const sync=()=>{const main=document.querySelector<HTMLElement>("main");const title=main?.querySelector("h1")?.textContent||"";if(!main)return;const detected=title.includes("Configuração de pontos")?"points":title==="Desafios"?"challenges":null;setSection(detected);if(customPage){main.classList.add("admin-custom-active");let el=main.querySelector<HTMLElement>("[data-admin-custom-page]");if(!el){el=document.createElement("div");el.dataset.adminCustomPage="1";main.prepend(el)}setHost(el);return;}main.classList.remove("admin-custom-active");main.querySelector("[data-admin-custom-page]")?.remove();let el=main.querySelector<HTMLElement>("[data-admin-config-section]");if(detected){if(!el){el=document.createElement("div");el.dataset.adminConfigSection="1";const controls=main.querySelector("[data-admin-controls]");controls?.insertAdjacentElement("afterend",el);if(!controls)main.prepend(el)}setHost(el)}else{el?.remove();setHost(null)}};
  const injectMenu=()=>{const aside=document.querySelector("aside");if(!aside||aside.querySelector("[data-admin-extra-menu]"))return;const adminLabel=Array.from(aside.querySelectorAll("div")).find(el=>el.textContent?.trim()==="Administração");const section=adminLabel?.parentElement;if(!section)return;const wrap=document.createElement("div");wrap.dataset.adminExtraMenu="1";wrap.className="admin-extra-menu";wrap.innerHTML='<button data-admin-extra="wheel"><span>🎰</span>Roleta</button><button data-admin-extra="guide"><span>📘</span>Guia de uso</button>';section.appendChild(wrap)};
  const click=(event:MouseEvent)=>{const target=event.target;if(!(target instanceof Element))return;const extra=target.closest<HTMLElement>("[data-admin-extra]");if(extra){event.preventDefault();event.stopPropagation();setCustomPage(extra.dataset.adminExtra as AdminCustomPage);requestAnimationFrame(sync);return;}const button=target.closest("aside button");if(button&&!button.closest("[data-admin-extra]")){setCustomPage(null);requestAnimationFrame(sync)}};
  sync();injectMenu();const observer=new MutationObserver(()=>requestAnimationFrame(()=>{sync();injectMenu()}));observer.observe(document.body,{childList:true,subtree:true,characterData:true});document.addEventListener("click",click,true);return()=>{observer.disconnect();document.removeEventListener("click",click,true);document.querySelector("main")?.classList.remove("admin-custom-active")};
 },[customPage]);
 const upsertRule=(rule:Rule)=>{const next=rules.some(item=>item.id===rule.id)?rules.map(item=>item.id===rule.id?rule:item):[...rules,rule];setRules(next);save(RULES_KEY,next);setRuleEdit(null);flash("Regra de pontuação salva.")};
 const upsertChallenge=(challenge:Challenge)=>{const next=challenges.some(item=>item.id===challenge.id)?challenges.map(item=>item.id===challenge.id?challenge:item):[...challenges,challenge];setChallenges(next);save(CHALLENGES_KEY,next);setChallengeEdit(null);flash("Desafio salvo com sucesso.")};
 const persistWheel=()=>{save(WHEEL_KEY,wheel);window.dispatchEvent(new CustomEvent("orbion-wheel-config-updated"));flash("Premiações da roleta atualizadas.")};
 return <>{host&&section==="points"&&!customPage&&createPortal(<RulesManager rules={rules} setRules={setRules} edit={setRuleEdit} flash={flash}/>,host)}{host&&section==="challenges"&&!customPage&&createPortal(<ChallengesManager challenges={challenges} edit={setChallengeEdit}/>,host)}{host&&customPage==="wheel"&&createPortal(<WheelAdmin wheel={wheel} setWheel={setWheel} save={persistWheel}/>,host)}{host&&customPage==="guide"&&createPortal(<UsageGuide onOpenWheel={()=>setCustomPage("wheel")}/>,host)}{ruleEdit&&<RuleEditor rule={ruleEdit} onClose={()=>setRuleEdit(null)} onSave={upsertRule}/>} {challengeEdit&&<ChallengeEditor challenge={challengeEdit} onClose={()=>setChallengeEdit(null)} onSave={upsertChallenge}/>} {toast&&<div className="admin-config-toast"><CheckCircle2 className="h-4 w-4"/>{toast}</div>}</>;
}
function RulesManager({rules,setRules,edit,flash}:{rules:Rule[];setRules:(rules:Rule[])=>void;edit:(rule:Rule)=>void;flash:(message:string)=>void}){const toggle=(id:string)=>{const next=rules.map(rule=>rule.id===id?{...rule,active:!rule.active}:rule);setRules(next);save(RULES_KEY,next);flash("Status da regra atualizado.")};return <section className="config-card"><Header icon={<Zap/>} kicker="REGRAS CONFIGURÁVEIS" title="Pontuação por atividade" text="Edite as regras existentes ou crie novas regras. O lápis abre a pontuação, nome e status da regra." action={<button onClick={()=>edit({id:`rule-${Date.now()}`,name:"Nova regra",points:10,active:true})}><Plus/>Nova regra</button>}/><div className="config-list">{rules.map(rule=><article key={rule.id}><div className={`config-dot ${rule.active?"active":""}`}/><div><strong>{rule.name}</strong><span>{rule.active?"Regra ativa":"Regra inativa"}</span></div><b>+{rule.points} pts</b><button className="icon" onClick={()=>edit(rule)} title="Editar regra"><Pencil/></button><button className={`toggle ${rule.active?"on":""}`} onClick={()=>toggle(rule.id)}>{rule.active?"Ativa":"Inativa"}</button></article>)}</div></section>}
function ChallengesManager({challenges,edit}:{challenges:Challenge[];edit:(challenge:Challenge)=>void}){return <section className="config-card"><Header icon={<Swords/>} kicker="GESTÃO DE DESAFIOS" title="Criar e editar desafios" text="Cada desafio pode ser reaberto para alterar participantes, métrica, período, meta e recompensa." action={<button onClick={()=>edit({id:`challenge-${Date.now()}`,name:"Novo desafio",description:"",type:"Duelo",metric:"Reuniões",target:"",reward:"",period:"",participants:"",active:true})}><Plus/>Novo desafio</button>}/><div className="challenge-admin-grid">{challenges.map(item=><article key={item.id}><div className="challenge-admin-top"><span>{item.type}</span><button onClick={()=>edit(item)}><Pencil/>Editar</button></div><h3>{item.name}</h3><p>{item.description}</p><dl><div><dt>Métrica</dt><dd>{item.metric}</dd></div><div><dt>Meta</dt><dd>{item.target}</dd></div><div><dt>Prêmio</dt><dd>{item.reward}</dd></div><div><dt>Período</dt><dd>{item.period}</dd></div></dl></article>)}</div></section>}
function WheelAdmin({wheel,setWheel,save}:{wheel:WheelConfig;setWheel:(wheel:WheelConfig)=>void;save:()=>void}){const update=(mode:keyof WheelConfig,index:number,value:string)=>setWheel({...wheel,[mode]:wheel[mode].map((item,i)=>i===index?value:item)});const remove=(mode:keyof WheelConfig,index:number)=>{if(wheel[mode].length<=2)return;setWheel({...wheel,[mode]:wheel[mode].filter((_,i)=>i!==index)})};const add=(mode:keyof WheelConfig)=>setWheel({...wheel,[mode]:[...wheel[mode],"Nova premiação"]});return <div className="admin-custom-page"><Header icon={<Dices/>} kicker="ADMINISTRAÇÃO" title="Configuração da roleta" text="Edite os entregáveis da premiação. Depois de salvar, os nomes aparecem dentro da roleta usada pelos colaboradores." action={<button className="save-main" onClick={save}><Save/>Salvar alterações</button>}/><div className="wheel-admin-grid"><PrizeColumn title="Roleta Clássica" tone="blue" items={wheel.classic} update={(i,v)=>update("classic",i,v)} remove={i=>remove("classic",i)} add={()=>add("classic")}/><PrizeColumn title="Roleta Premium" tone="gold" items={wheel.premium} update={(i,v)=>update("premium",i,v)} remove={i=>remove("premium",i)} add={()=>add("premium")}/></div><div className="config-note"><Trophy/><div><strong>Como funciona a sincronização</strong><span>O colaborador vê exatamente os prêmios salvos aqui. O giro continua escolhendo um dos setores visíveis e o resultado mostrado corresponde ao setor onde o ponteiro parou.</span></div></div></div>}
function PrizeColumn({title,tone,items,update,remove,add}:{title:string;tone:string;items:string[];update:(index:number,value:string)=>void;remove:(index:number)=>void;add:()=>void}){return <section className={`prize-column ${tone}`}><div className="prize-column-head"><div><span>PREMIAÇÕES</span><h3>{title}</h3></div><b>{items.length} itens</b></div><div className="prize-editor-list">{items.map((item,index)=><div key={`${index}-${title}`}><span>{String(index+1).padStart(2,"0")}</span><input value={item} onChange={e=>update(index,e.target.value)} /><button onClick={()=>remove(index)} title="Remover prêmio"><Trash2/></button></div>)}</div><button className="add-prize" onClick={add}><Plus/>Adicionar premiação</button></section>}
function UsageGuide({onOpenWheel}:{onOpenWheel:()=>void}){const steps=[
["1","Cadastre o colaborador","Acesse Administração > Equipe e clique em Cadastrar colaborador. Preencha nome, e-mail, cargo, status, pontos iniciais e foto."],
["2","Edite o cadastro completo","Na lista de colaboradores clique no lápis Editar. Você pode trocar foto, cargo, equipe, telefone, status, meta, nível e pontos-base."],
["3","Faça lançamentos manuais","Use Lançar pontos para adicionar ou remover uma quantidade específica. Sempre registre o motivo para manter histórico e auditoria."],
["4","Configure regras de pontuação","Acesse Administração > Pontuação. O lápis abre cada regra existente. Você pode alterar o valor, renomear, ativar ou inativar e criar novas regras."],
["5","Gerencie desafios","Abra Desafios. Na área Gestão de Desafios use Editar para alterar participantes, métrica, meta, período e recompensa. O botão Novo desafio cria outro modelo."],
["6","Configure as roletas","Abra Administração > Roleta. Edite o texto de cada premiação, adicione ou remova itens e clique em Salvar alterações. A roleta do colaborador usa essa configuração."],
["7","Valide antes de usar","Confira Equipe, Pontuação, Desafios e Roleta. Faça um giro de teste e verifique se o prêmio exibido é o mesmo setor apontado pela roleta."]
];return <div className="admin-custom-page"><Header icon={<BookOpen/>} kicker="ADMINISTRAÇÃO" title="Guia de uso" text="Fluxo recomendado para configurar o MVP e operar a gamificação do time." action={<button onClick={onOpenWheel}><Dices/>Abrir configuração da roleta</button>}/><div className="guide-grid">{steps.map(([n,title,text])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><section className="guide-checklist"><ShieldCheck/><div><strong>Ordem recomendada de implantação</strong><p>1. Cadastre a equipe. 2. Revise regras de pontos. 3. Configure desafios. 4. Cadastre as premiações. 5. Teste a roleta. 6. Libere para os colaboradores.</p></div></section></div>}
function Header({icon,kicker,title,text,action}:{icon:React.ReactNode;kicker:string;title:string;text:string;action?:React.ReactNode}){return <div className="config-head"><div className="config-head-icon">{icon}</div><div className="config-head-copy"><span>{kicker}</span><h2>{title}</h2><p>{text}</p></div>{action&&<div className="config-head-action">{action}</div>}</div>}
function RuleEditor({rule,onClose,onSave}:{rule:Rule;onClose:()=>void;onSave:(rule:Rule)=>void}){const [form,setForm]=useState(rule);return <EditorModal title="Editar regra de pontuação" onClose={onClose}><Field label="Nome da regra"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Pontos"><input type="number" min="0" value={form.points} onChange={e=>setForm({...form,points:Number(e.target.value)})}/></Field><Field label="Status"><select value={form.active?"Ativa":"Inativa"} onChange={e=>setForm({...form,active:e.target.value==="Ativa"})}><option>Ativa</option><option>Inativa</option></select></Field><Footer onClose={onClose} onSave={()=>onSave(form)}/></EditorModal>}
function ChallengeEditor({challenge,onClose,onSave}:{challenge:Challenge;onClose:()=>void;onSave:(challenge:Challenge)=>void}){const [form,setForm]=useState(challenge);return <EditorModal title={challenge.id.startsWith("challenge-")?"Novo desafio":"Editar desafio"} onClose={onClose}><Field label="Nome"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Descrição"><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="editor-two"><Field label="Tipo"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as Challenge["type"]})}><option>Duelo</option><option>Coletivo</option></select></Field><Field label="Métrica"><select value={form.metric} onChange={e=>setForm({...form,metric:e.target.value})}><option>Reuniões</option><option>Vendas</option><option>Faturamento</option><option>Pontos</option><option>Atividades</option></select></Field></div><Field label="Participantes"><input value={form.participants} onChange={e=>setForm({...form,participants:e.target.value})} placeholder="Ex.: Marcelo x Lucas"/></Field><div className="editor-two"><Field label="Meta"><input value={form.target} onChange={e=>setForm({...form,target:e.target.value})}/></Field><Field label="Período"><input value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></Field></div><Field label="Recompensa"><input value={form.reward} onChange={e=>setForm({...form,reward:e.target.value})}/></Field><Footer onClose={onClose} onSave={()=>onSave(form)}/></EditorModal>}
function EditorModal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="config-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="config-modal"><button className="config-close" onClick={onClose}><X/></button><div className="config-modal-title"><ShieldCheck/><div><span>ADMINISTRAÇÃO</span><h2>{title}</h2></div></div>{children}</section></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="config-field"><span>{label}</span>{children}</label>}
function Footer({onClose,onSave}:{onClose:()=>void;onSave:()=>void}){return <div className="config-footer"><button onClick={onClose}>Cancelar</button><button className="save" onClick={onSave}><Save/>Salvar</button></div>}
