import { useEffect, useMemo, useState, type ChangeEvent } from "react";
import { createPortal } from "react-dom";
import { Camera, CheckCircle2, Pencil, Search, ShieldCheck, UserRoundCog, Users, X } from "lucide-react";
import "./admin-roster.css";

type Person={id:string;name:string;role:string;email:string;points:number;photo?:string;status:"Ativo"|"Inativo";phone?:string;team?:string;goal?:number;level?:number};
type Entry={personId:string;amount:number;type:"add"|"remove"};
const PEOPLE_KEY="orbion-admin-people-v1";
const OVERRIDES_KEY="orbion-admin-people-overrides-v2";
const ENTRIES_KEY="orbion-admin-entries-v1";
const base:Person[]=[
{id:"joao",name:"João Martins",role:"Closer",email:"joao@orbion.com.br",points:3480,status:"Ativo",team:"Vendas",goal:50000,level:8},
{id:"amanda",name:"Amanda Silva",role:"SDR",email:"amanda@orbion.com.br",points:3120,status:"Ativo",team:"Pré-vendas",goal:80,level:8},
{id:"marcelo",name:"Marcelo Alves",role:"Closer",email:"marcelo@orbion.com.br",points:2950,status:"Ativo",team:"Vendas",goal:50000,level:7},
{id:"lucas",name:"Lucas Rocha",role:"Closer",email:"lucas@orbion.com.br",points:2700,status:"Ativo",team:"Vendas",goal:50000,level:7},
{id:"gabriel",name:"Gabriel Lima",role:"SDR",email:"gabriel@orbion.com.br",points:2540,status:"Ativo",team:"Pré-vendas",goal:80,level:6},
{id:"carolina",name:"Carolina Melo",role:"Closer",email:"carolina@orbion.com.br",points:2310,status:"Ativo",team:"Vendas",goal:50000,level:6},
];
function initials(name:string){return name.trim().split(/\s+/).slice(0,2).map(v=>v[0]?.toUpperCase()||"").join("")}
function getList<T>(key:string):T[]{try{return JSON.parse(localStorage.getItem(key)||"[]") as T[]}catch{return[]}}
function getMap<T>(key:string):Record<string,T>{try{return JSON.parse(localStorage.getItem(key)||"{}") as Record<string,T>}catch{return{}}}
export function AdminRoster(){
 const [host,setHost]=useState<HTMLElement|null>(null); const [people,setPeople]=useState<Person[]>([]); const [overrides,setOverrides]=useState<Record<string,Partial<Person>>>({}); const [entries,setEntries]=useState<Entry[]>([]); const [query,setQuery]=useState(""); const [editing,setEditing]=useState<Person|null>(null); const [toast,setToast]=useState<string|null>(null);
 useEffect(()=>{const sync=()=>{const main=document.querySelector<HTMLElement>("main");const title=main?.querySelector("h1")?.textContent||"";if(!main||!title.includes("Gestão da equipe")){setHost(null);return;}let el=main.querySelector<HTMLElement>("[data-admin-roster]");if(!el){el=document.createElement("div");el.dataset.adminRoster="1";const toolbar=main.querySelector("[data-admin-controls]");toolbar?.insertAdjacentElement("afterend",el);if(!toolbar)main.prepend(el);}setHost(el);};const load=()=>{setPeople(getList<Person>(PEOPLE_KEY));setOverrides(getMap<Partial<Person>>(OVERRIDES_KEY));setEntries(getList<Entry>(ENTRIES_KEY));};sync();load();const observer=new MutationObserver(()=>requestAnimationFrame(sync));observer.observe(document.body,{childList:true,subtree:true,characterData:true});const timer=window.setInterval(load,700);return()=>{observer.disconnect();clearInterval(timer)}} ,[]);
 const adjustment=useMemo(()=>entries.reduce<Record<string,number>>((a,e)=>{a[e.personId]=(a[e.personId]||0)+(e.type==="add"?e.amount:-e.amount);return a},{}),[entries]);
 const mergedBase=base.map(person=>({...person,...(overrides[person.id]||{})}));
 const all=[...mergedBase,...people].filter(p=>`${p.name} ${p.role} ${p.email} ${p.team||""}`.toLowerCase().includes(query.toLowerCase()));
 const displayPoints=(person:Person)=>person.points+(adjustment[person.id]||0);
 const savePerson=(person:Person)=>{
   const isBase=base.some(item=>item.id===person.id);
   if(isBase){const next={...overrides,[person.id]:person};setOverrides(next);localStorage.setItem(OVERRIDES_KEY,JSON.stringify(next));}
   else{const next=people.map(item=>item.id===person.id?person:item);setPeople(next);localStorage.setItem(PEOPLE_KEY,JSON.stringify(next));}
   setEditing(null);setToast(`${person.name} atualizado com sucesso.`);window.setTimeout(()=>setToast(null),2500);
 };
 if(!host)return <>{editing&&<EditPersonModal person={editing} currentPoints={displayPoints(editing)} onClose={()=>setEditing(null)} onSave={savePerson}/>}</>;
 return <>{createPortal(<section className="admin-roster-section"><div className="admin-roster-head"><div><div className="admin-roster-kicker"><ShieldCheck className="h-4 w-4"/>CADASTRO OPERACIONAL</div><h2>Colaboradores do time</h2><p>Abra o cadastro completo para trocar foto, cargo, status, meta, nível, dados de contato e pontuação-base.</p></div><span><Users className="h-4 w-4"/>{all.length} pessoas</span></div><label className="admin-roster-search"><Search className="h-4 w-4"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar colaborador"/></label><div className="admin-roster-grid">{all.map(person=><article key={person.id}><div className="admin-roster-avatar">{person.photo?<img src={person.photo} alt={person.name}/>:<span>{initials(person.name)}</span>}</div><div className="admin-roster-copy"><strong>{person.name}</strong><span>{person.role}{person.team?` · ${person.team}`:""}</span><small>{person.email}</small></div><div className="admin-roster-points"><span>Pontos</span><strong>{displayPoints(person).toLocaleString("pt-BR")}</strong></div><div className={`admin-roster-status ${person.status==="Ativo"?"active":""}`}>{person.status}</div><button className="admin-edit-person" onClick={()=>setEditing(person)}><Pencil className="h-3.5 w-3.5"/>Editar</button></article>)}</div></section>,host)}{editing&&<EditPersonModal person={editing} currentPoints={displayPoints(editing)} onClose={()=>setEditing(null)} onSave={savePerson}/>} {toast&&<div className="admin-roster-toast"><CheckCircle2 className="h-4 w-4"/>{toast}</div>}</>;
}

function EditPersonModal({person,currentPoints,onClose,onSave}:{person:Person;currentPoints:number;onClose:()=>void;onSave:(person:Person)=>void}){
 const [form,setForm]=useState<Person>({...person}); const [error,setError]=useState<string|null>(null);
 const photoChange=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")||file.size>1500000){setError("Use uma imagem JPG, PNG ou WEBP de até 1,5 MB.");return;}const reader=new FileReader();reader.onload=()=>{if(typeof reader.result==="string")setForm(current=>({...current,photo:reader.result as string}))};reader.readAsDataURL(file);setError(null)};
 const update=(key:keyof Person,value:string|number)=>setForm(current=>({...current,[key]:value}));
 const submit=()=>{if(!form.name.trim())return setError("Informe o nome do colaborador.");if(!form.email.includes("@"))return setError("Informe um e-mail válido.");onSave({...form,points:Math.max(0,Number(form.points)||0),goal:Math.max(0,Number(form.goal)||0),level:Math.max(1,Number(form.level)||1)});};
 return <div className="admin-roster-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="admin-roster-modal"><button className="admin-roster-close" onClick={onClose}><X className="h-5 w-5"/></button><div className="admin-roster-modal-head"><div className="admin-roster-kicker"><UserRoundCog className="h-4 w-4"/>EDITAR COLABORADOR</div><h2>Cadastro completo</h2><p>Edite tudo que se refere a este colaborador. Os ajustes ficam salvos no MVP.</p></div><div className="admin-roster-form"><div className="admin-roster-photo-column"><div className="admin-roster-photo">{form.photo?<img src={form.photo} alt={form.name}/>:<span>{initials(form.name)}</span>}</div><label><Camera className="h-4 w-4"/>Trocar foto<input type="file" accept="image/*" onChange={photoChange}/></label><small>JPG, PNG ou WEBP até 1,5 MB</small></div><div className="admin-roster-fields"><Field label="Nome completo"><input value={form.name} onChange={e=>update("name",e.target.value)}/></Field><Field label="E-mail"><input type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></Field><div className="admin-roster-two"><Field label="Cargo"><select value={form.role} onChange={e=>update("role",e.target.value)}><option>SDR</option><option>Closer</option><option>Social Seller</option><option>Supervisor Comercial</option><option>Gestor</option></select></Field><Field label="Status"><select value={form.status} onChange={e=>update("status",e.target.value)}><option>Ativo</option><option>Inativo</option></select></Field></div><div className="admin-roster-two"><Field label="Equipe"><input value={form.team||""} onChange={e=>update("team",e.target.value)} placeholder="Ex.: Vendas"/></Field><Field label="Telefone"><input value={form.phone||""} onChange={e=>update("phone",e.target.value)} placeholder="(27) 99999-9999"/></Field></div><div className="admin-roster-three"><Field label="Pontos-base"><input type="number" min="0" value={form.points} onChange={e=>update("points",e.target.value)}/></Field><Field label="Nível"><input type="number" min="1" value={form.level||1} onChange={e=>update("level",e.target.value)}/></Field><Field label="Meta"><input type="number" min="0" value={form.goal||0} onChange={e=>update("goal",e.target.value)}/></Field></div><div className="admin-current-points"><span>Saldo atual considerando lançamentos</span><strong>{currentPoints.toLocaleString("pt-BR")} pts</strong></div></div></div>{error&&<div className="admin-roster-error">{error}</div>}<div className="admin-roster-footer"><button onClick={onClose}>Cancelar</button><button className="save" onClick={submit}><CheckCircle2 className="h-4 w-4"/>Salvar alterações</button></div></section></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="admin-roster-field"><span>{label}</span>{children}</label>}
