/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AguardandoRouteImport } from './routes/aguardando'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppConquistasRouteImport } from './routes/_app/conquistas'
import { Route as AppDesafiosRouteImport } from './routes/_app/desafios'
import { Route as AppMissoesRouteImport } from './routes/_app/missoes'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppRankingRouteImport } from './routes/_app/ranking'
import { Route as AppRecompensasRouteImport } from './routes/_app/recompensas'
import { Route as AppRoletaRouteImport } from './routes/_app/roleta'
import { Route as DevShowcaseRouteImport } from './routes/dev/showcase'
import { Route as AppAdminAdminIndexRouteImport } from './routes/_app/_admin/admin/index'
import { Route as AppAdminAdminConfiguracoesRouteImport } from './routes/_app/_admin/admin/configuracoes'
import { Route as AppAdminAdminEquipeRouteImport } from './routes/_app/_admin/admin/equipe'
import { Route as AppAdminAdminGuiaRouteImport } from './routes/_app/_admin/admin/guia'
import { Route as AppAdminAdminPontuacaoRouteImport } from './routes/_app/_admin/admin/pontuacao'
import { Route as AppAdminAdminRecompensasRouteImport } from './routes/_app/_admin/admin/recompensas'
import { Route as AppAdminAdminRoletaRouteImport } from './routes/_app/_admin/admin/roleta'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoRoute = AguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConquistasRoute = AppConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AppRoute,
} as any)
const AppDesafiosRoute = AppDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AppRoute,
} as any)
const AppMissoesRoute = AppMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppRecompensasRoute = AppRecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => AppRoute,
} as any)
const AppRoletaRoute = AppRoletaRouteImport.update({
  id: '/roleta',
  path: '/roleta',
  getParentRoute: () => AppRoute,
} as any)
const DevShowcaseRoute = DevShowcaseRouteImport.update({
  id: '/dev/showcase',
  path: '/dev/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAdminIndexRoute = AppAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminConfiguracoesRoute =
  AppAdminAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminAdminEquipeRoute = AppAdminAdminEquipeRouteImport.update({
  id: '/admin/equipe',
  path: '/admin/equipe',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminGuiaRoute = AppAdminAdminGuiaRouteImport.update({
  id: '/admin/guia',
  path: '/admin/guia',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminPontuacaoRoute = AppAdminAdminPontuacaoRouteImport.update({
  id: '/admin/pontuacao',
  path: '/admin/pontuacao',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminRecompensasRoute =
  AppAdminAdminRecompensasRouteImport.update({
    id: '/admin/recompensas',
    path: '/admin/recompensas',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminAdminRoletaRoute = AppAdminAdminRoletaRouteImport.update({
  id: '/admin/roleta',
  path: '/admin/roleta',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conquistas': typeof AppConquistasRoute
  '/desafios': typeof AppDesafiosRoute
  '/missoes': typeof AppMissoesRoute
  '/perfil': typeof AppPerfilRoute
  '/ranking': typeof AppRankingRoute
  '/recompensas': typeof AppRecompensasRoute
  '/roleta': typeof AppRoletaRoute
  '/dev/showcase': typeof DevShowcaseRoute
  '/admin/configuracoes': typeof AppAdminAdminConfiguracoesRoute
  '/admin/equipe': typeof AppAdminAdminEquipeRoute
  '/admin/guia': typeof AppAdminAdminGuiaRoute
  '/admin/pontuacao': typeof AppAdminAdminPontuacaoRoute
  '/admin/recompensas': typeof AppAdminAdminRecompensasRoute
  '/admin/roleta': typeof AppAdminAdminRoletaRoute
  '/admin/': typeof AppAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AppIndexRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conquistas': typeof AppConquistasRoute
  '/desafios': typeof AppDesafiosRoute
  '/missoes': typeof AppMissoesRoute
  '/perfil': typeof AppPerfilRoute
  '/ranking': typeof AppRankingRoute
  '/recompensas': typeof AppRecompensasRoute
  '/roleta': typeof AppRoletaRoute
  '/dev/showcase': typeof DevShowcaseRoute
  '/admin/configuracoes': typeof AppAdminAdminConfiguracoesRoute
  '/admin/equipe': typeof AppAdminAdminEquipeRoute
  '/admin/guia': typeof AppAdminAdminGuiaRoute
  '/admin/pontuacao': typeof AppAdminAdminPontuacaoRoute
  '/admin/recompensas': typeof AppAdminAdminRecompensasRoute
  '/admin/roleta': typeof AppAdminAdminRoletaRoute
  '/admin': typeof AppAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/conquistas': typeof AppConquistasRoute
  '/_app/desafios': typeof AppDesafiosRoute
  '/_app/missoes': typeof AppMissoesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/recompensas': typeof AppRecompensasRoute
  '/_app/roleta': typeof AppRoletaRoute
  '/dev/showcase': typeof DevShowcaseRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_admin/admin/configuracoes': typeof AppAdminAdminConfiguracoesRoute
  '/_app/_admin/admin/equipe': typeof AppAdminAdminEquipeRoute
  '/_app/_admin/admin/guia': typeof AppAdminAdminGuiaRoute
  '/_app/_admin/admin/pontuacao': typeof AppAdminAdminPontuacaoRoute
  '/_app/_admin/admin/recompensas': typeof AppAdminAdminRecompensasRoute
  '/_app/_admin/admin/roleta': typeof AppAdminAdminRoletaRoute
  '/_app/_admin/admin/': typeof AppAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando'
    | '/login'
    | '/signup'
    | '/configuracoes'
    | '/conquistas'
    | '/desafios'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/recompensas'
    | '/roleta'
    | '/dev/showcase'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/guia'
    | '/admin/pontuacao'
    | '/admin/recompensas'
    | '/admin/roleta'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aguardando'
    | '/login'
    | '/signup'
    | '/'
    | '/configuracoes'
    | '/conquistas'
    | '/desafios'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/recompensas'
    | '/roleta'
    | '/dev/showcase'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/guia'
    | '/admin/pontuacao'
    | '/admin/recompensas'
    | '/admin/roleta'
    | '/admin'
  id:
    | '__root__'
    | '/_app'
    | '/aguardando'
    | '/login'
    | '/signup'
    | '/_app/_admin'
    | '/_app/configuracoes'
    | '/_app/conquistas'
    | '/_app/desafios'
    | '/_app/missoes'
    | '/_app/perfil'
    | '/_app/ranking'
    | '/_app/recompensas'
    | '/_app/roleta'
    | '/dev/showcase'
    | '/_app/'
    | '/_app/_admin/admin/configuracoes'
    | '/_app/_admin/admin/equipe'
    | '/_app/_admin/admin/guia'
    | '/_app/_admin/admin/pontuacao'
    | '/_app/_admin/admin/recompensas'
    | '/_app/_admin/admin/roleta'
    | '/_app/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AguardandoRoute: typeof AguardandoRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DevShowcaseRoute: typeof DevShowcaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando': {
      id: '/aguardando'
      path: '/aguardando'
      fullPath: '/aguardando'
      preLoaderRoute: typeof AguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conquistas': {
      id: '/_app/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AppConquistasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/desafios': {
      id: '/_app/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AppDesafiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missoes': {
      id: '/_app/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof AppMissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recompensas': {
      id: '/_app/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof AppRecompensasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roleta': {
      id: '/_app/roleta'
      path: '/roleta'
      fullPath: '/roleta'
      preLoaderRoute: typeof AppRoletaRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/showcase': {
      id: '/dev/showcase'
      path: '/dev/showcase'
      fullPath: '/dev/showcase'
      preLoaderRoute: typeof DevShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_admin/admin/': {
      id: '/_app/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/configuracoes': {
      id: '/_app/_admin/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AppAdminAdminConfiguracoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/equipe': {
      id: '/_app/_admin/admin/equipe'
      path: '/admin/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AppAdminAdminEquipeRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/guia': {
      id: '/_app/_admin/admin/guia'
      path: '/admin/guia'
      fullPath: '/admin/guia'
      preLoaderRoute: typeof AppAdminAdminGuiaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/pontuacao': {
      id: '/_app/_admin/admin/pontuacao'
      path: '/admin/pontuacao'
      fullPath: '/admin/pontuacao'
      preLoaderRoute: typeof AppAdminAdminPontuacaoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/recompensas': {
      id: '/_app/_admin/admin/recompensas'
      path: '/admin/recompensas'
      fullPath: '/admin/recompensas'
      preLoaderRoute: typeof AppAdminAdminRecompensasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/roleta': {
      id: '/_app/_admin/admin/roleta'
      path: '/admin/roleta'
      fullPath: '/admin/roleta'
      preLoaderRoute: typeof AppAdminAdminRoletaRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAdminConfiguracoesRoute: typeof AppAdminAdminConfiguracoesRoute
  AppAdminAdminEquipeRoute: typeof AppAdminAdminEquipeRoute
  AppAdminAdminGuiaRoute: typeof AppAdminAdminGuiaRoute
  AppAdminAdminPontuacaoRoute: typeof AppAdminAdminPontuacaoRoute
  AppAdminAdminRecompensasRoute: typeof AppAdminAdminRecompensasRoute
  AppAdminAdminRoletaRoute: typeof AppAdminAdminRoletaRoute
  AppAdminAdminIndexRoute: typeof AppAdminAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAdminConfiguracoesRoute: AppAdminAdminConfiguracoesRoute,
  AppAdminAdminEquipeRoute: AppAdminAdminEquipeRoute,
  AppAdminAdminGuiaRoute: AppAdminAdminGuiaRoute,
  AppAdminAdminPontuacaoRoute: AppAdminAdminPontuacaoRoute,
  AppAdminAdminRecompensasRoute: AppAdminAdminRecompensasRoute,
  AppAdminAdminRoletaRoute: AppAdminAdminRoletaRoute,
  AppAdminAdminIndexRoute: AppAdminAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConquistasRoute: typeof AppConquistasRoute
  AppDesafiosRoute: typeof AppDesafiosRoute
  AppMissoesRoute: typeof AppMissoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingRoute: typeof AppRankingRoute
  AppRecompensasRoute: typeof AppRecompensasRoute
  AppRoletaRoute: typeof AppRoletaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConquistasRoute: AppConquistasRoute,
  AppDesafiosRoute: AppDesafiosRoute,
  AppMissoesRoute: AppMissoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingRoute: AppRankingRoute,
  AppRecompensasRoute: AppRecompensasRoute,
  AppRoletaRoute: AppRoletaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AguardandoRoute: AguardandoRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DevShowcaseRoute: DevShowcaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
